name: gas_05_2017Dart
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: raz <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
#  path: ^1.4.1
  http: ^0.11.3+13

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
#  http: ^0.11.3+9
  intl: ^0.15.0

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
# Doesn't work for this proj:
#  Could not find asset gas_05_2017Dart|web/dart_stack_trace_mapper.js.map.
#  Could not find asset gas_05_2017Dart|web/dart_sdk.js.map.
#web:
#  compiler:
#    debug: dartdevc